name: cards
description: "Card Games, a 9 Cards Golf and Skyjo"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.11.6

environment:
  sdk: ^3.11.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  animate_do: ^4.2.0
  firebase_auth: ^6.2.0
  firebase_core: ^4.5.0
  firebase_database: ^12.1.4
  flutter:
    sdk: flutter
  google_sign_in: ^7.2.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  intl: ^0.20.2
  logger: ^2.6.2
  mockito: ^5.6.3
  package_info_plus: ^9.0.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  the_splash: ^0.3.1
  universal_platform: ^1.1.0
  url_launcher: ^6.3.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  mocktail: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/table_top.png
    - assets/images/back_of_card.png
    - assets/generated/
      # for read the config
    - flutter_native_splash.yaml

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: GameFont
      fonts:
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Regular.ttf
  generate: true

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios:
    remove_alpha_ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
  macos:
    generate: true
    image_path: "assets/app_icon.png"
